name: 'Maven Package and Deploy Remote'
description: 'package the java Maven project and deploy to remote server'
author: 'discko'
inputs: 
  java-version:
    description: 'The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28'
    require: true
outputs:
  result:
    description: 'Process result'
    value: 
runs:
  using: "composite"
  steps:
    - name: first step
      shell: bash
      run: |
        echo "inputs1:"$INPUT_JAVA_VERSION
        echo "inputs2:"${{inputs.java-version"}}
        pwd
        ls
        
    - name: checkout
      uses: actions/checkout@master

    - name: second step
      id: MainStep
      shell: bash
      run: |
        pwd
        ls
        echo "::Set-output name=out::"process result"
